# Generated by Django 3.0.8 on 2021-04-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('bike_model', models.CharField(max_length=20)),
                ('wheel_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('brakes_mounts', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('wheel_model', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('brakes', models.CharField(max_length=20)),
            ],
        ),
    ]
