# Generated by Django 3.0.8 on 2021-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheels',
            name='back',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wheels',
            name='front',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='wheel_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
